version: "3.7"

services:
  postgres_base:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: usermanagement
      POSTGRES_PASSWORD: password10
      POSTGRES_DB: user
    networks:
      - app_net
    volumes:
      - db-cache:/var/lib/postgresql/data
    ports:
      - 5434:5432
  dev:
    image: gradle:5.6.3-jdk11
    working_dir: /app
    volumes:
      - .:/app
      - gradle-cache:/home/gradle/.gradle
    networks:
      - app_net
    env_file:
      - docker.app.env
    ports:
      - 8082:8080
      - 5007:5005
    command: gradle bootRun
    depends_on:
      - postgres_base
networks:
  app_net:

volumes:
  db-cache:
  gradle-cache:
