spring:
  application:
    name: service-user-management
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

app:
  env: local
  search:
    sort:
      by: id
      direction: desc
    pageSize: 2
    maxSize: 10
    page: 0

info:
  app:
    version: 1.0.0
    test: test
    name: user-management-api-actuator

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  server:
    servlet:
      context-path: /monitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9001
